routes/web.php
<?php

use App\Http\Controllers\AirdropController;
use App\Http\Controllers\AirdropCrud;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\TesterController;
use App\Http\Middleware\LoginMiddleware;
use App\Http\Middleware\NotLoginMiddleware;
use App\Http\Middleware\SessionCheck;
use App\Models\DBAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

/*
 *
 * FOR LOGGED USER
 */
Route::middleware(LoginMiddleware::class)->group(function () {
    Route::get('/', [AirdropController::class, 'index']);
    Route::get('/data{any}', [AirdropController::class, 'data_list'])->where('any', '.*');
    Route::get('/new{any}', [AirdropController::class, 'data_create'])->where('any', '.*');
    Route::get('/show/{id}', [AirdropController::class, 'show']);
    Route::get('/edit/{id}', [AirdropController::class, 'update']);
    Route::get('/setting', [AirdropController::class, 'setting']);
    Route::get('/notifications', [AirdropController::class, 'notif']);
});

Route::get('test', [TesterController::class, "index"]);

/*
 * ROUTE FOR NON LOGIN
 *
 */
Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
    /* PUBLIC */
    Route::any('error', [LoginController::class, 'error_json']);

    /* FOR NOT LOGGED  */
    Route::middleware(NotLoginMiddleware::class)->group(function () {
        Route::get("/", [LoginController::class, "index"]);
        Route::any('check', [LoginController::class, "check"])->name('check');
    });

    /* FOR LOGGED */
    Route::middleware(LoginMiddleware::class)->group(function () {
        Route::get('logout', [LoginController::class, 'logout']);
    });
});

/* JSON REQUEST CRUD AIRDROP */
Route::group(['middleware' => SessionCheck::class, 'prefix' => 'airdrop_request'], function () {
    /* THIS ROUTE REQUIRES token Input */
    Route::get('/', [AirdropCrud::class, 'index']);
});

app/Http/Controllers/AirdropController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\AppHelper;
use App\Models\Airdrop;
use App\Models\AirdropModel;
use App\Models\AuthModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AirdropController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(AuthModel $a)
    {
        AppHelper::CheckNotif();
        // return view("dashboard");
        return \view('page-wire', [
            'pageWire' => 'page-dashboard',
            'name' => 'Dashboard',
            // 'pathName' => 'Page Settings',
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function data_list()
    {
        return \view('page-wire', [
            'pageWire' => 'page-list',
            'name' => 'Projects',
            'title' => 'PROJECT LIST',
            'pathName' => 'Project Lists',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function data_create(Request $request)
    {
        return \view('page-wire', [
            'pageWire' => 'page-create',
            'name' => 'Projects',
            'title' => 'NEW PROJECT',
            'pathName' => 'Add New Project',
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Airdrop  $airdrop
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request, AirdropModel $a)
    {
        $name = AirdropModel::where('id', $id)->first();

        if ($name) {
            return \view('page-wire', [
                'pageWire' => 'page-show',
                'name' => 'Project Details',
                'pathName' => 'ID: ' . $name->name,
                // 'ids' => $id,
            ]);} else {
            return \abort(404);
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Airdrop  $airdrop
     * @return \Illuminate\Http\Response
     */
    public function setting()
    {
        return \view('page-wire', [
            'pageWire' => 'page-settings',
            'name' => 'Settings',
            'title' => 'SETTINGS',
            'pathName' => 'Page Settings',
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Airdrop  $airdrop
     * @return \Illuminate\Http\Response
     */
    public function notif(Request $request)
    {
        return \view('page-wire', [
            'pageWire' => 'page-notif',
            'name' => 'Notification',
            'title' => 'NOTIFICATIONS',
            'pathName' => 'Notification Lists',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Airdrop  $airdrop
     * @return \Illuminate\Http\Response
     */
    public function update(AirdropModel $a, $id)
    {
        $name = AirdropModel::where('id', $id)->first();

        if ($name) {
            return \view('page-wire', [
                'pageWire' => 'page-edit',
                'name' => 'Edit Project',
                'title' => \strtoupper($name->name),
                'pathName' => 'ID: ' . $name->name,
                // 'ids' => $id,
            ]);} else {
            return \abort(404);
        }
    }

    /**
     * LOGIN
     *
     */
    public function login(DB $db, Auth $auth)
    {
        echo \view('airdrop.login');
    }
}

resources/views/airdrop/create.blade.php
@extends('layouts.app')

@section('title', 'ADD LIST')

@section('content')

@endsection

@section('vuehead')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css">
    <script>
        let currentPath = "{{ Request::getRequestUri() }}"
        let siteurl = "{{ url('/') }}"
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
    <script defer src="{{ asset('js/create.js') }}"></script>
@endsection
{{-- <div id="vue">
    <example-component></example-component>
</div> --}}

resources/views/airdrop/index.blade.php
@extends('layouts.app')

@section('title', 'INDEX')

@section('content')

    {{ \App\Models\DBAdmin::first()->sitename }}

@endsection

resources/views/airdrop/list.blade.php
@extends('layouts.app')

@section('title', 'ADD LIST')

@section('content')

@endsection

@section('vuehead')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css">
    <script>
        let currentPath = "{{ Request::getRequestUri() }}"
        let siteurl = "{{ url('/') }}"
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>

    <script defer src="{{ asset('js/list.js') }}"></script>
@endsection
{{-- <div id="vue">
    <example-component></example-component>
</div> --}}

resources/views/airdrop/login.blade.php
@extends('layouts.auth')

@section('bodyclass', 'hold-transition login-page')
@section('appclass', 'login-box')

@section('content')

    <div class="login-logo">
        <a href="../../index2.html"><b>LOGIN</b> AREA</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>

            <div id="form">
                @csrf
                <div class="input-group mb-3">
                    {{-- <input type="hidden" name="method_field" value="PUT"> --}}
                    <input type="password" class="form-control" id='password' name="password" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div id="error" class="valid-feedback">aaa</div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="button" id="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </div>

        </div>
        <!-- /.login-card-body -->
    </div>
    {{-- END CARD LOGIN --}}

@endsection

@section('script')

    <script>
        $pom = function() {
            $data = $("#form :input").serialize()
            console.log($data);
            $('#form :input').prop('disabled', true)

            $req = $.post("{{ route('auth.check') }}", $data, function(data) {
                var obj = JSON.parse(JSON.stringify(data))
                if (obj.status == true) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Login Berhasil!',
                    })

                    setTimeout(function() {
                        window.location = "{{ url('/auth?token=') }}" + obj.data.token
                    }, 1000)
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Login Gagal!',
                        text: 'Password tidak valid!',
                    })
                }

            })

            $req.done(function() {
                $('#form :input').prop('disabled', false)
            })
        }

        $("#submit").click($pom)
        $("#password").bind("enterKey", $pom);
        $("#password").keyup(function(e) {
            e.keyCode == 13 ? $(this).trigger("enterKey") : ""
        });
    </script>

@endsection

resources/views/airdrop/show.blade.php
@extends('layouts.app')

@section('title', 'DETAILS')


@section('content')

@endsection

@section('vuehead')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css">
    <script>
        let currentPath = "{{ Request::getRequestUri() }}"
        let siteurl = "{{ url('/') }}"
        let showID = {{ $showID }}
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
    <script defer src="{{ asset('js/show.js') }}"></script>
@endsection
{{-- <div id="vue">
    <example-component></example-component>
</div> --}}